apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quarkus-quay-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-quay-test
    app.kubernetes.io/part-of: test
  name: quarkus-quay-test
  namespace: mdsaud
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: quarkus-quay-test
status:
  loadBalancer: {}
